import React from 'react';

export const IndexPage = () => (
  <div className="index-container">
    
    <p>Succulents gastropub vape portland, direct trade shabby chic cornhole. Kinfolk cornhole yuccie, food truck poke trust fund pinterest pour-over selvage normcore. Gluten-free four dollar toast edison bulb banjo, sartorial bitters sustainable vegan. Skateboard hammock hoodie hell of unicorn, jianbing actually truffaut lumbersexual sartorial. Man bun vaporware typewriter ugh, taiyaki gluten-free tbh hot chicken fingerstache cold-pressed normcore shoreditch pabst subway tile. Bushwick chartreuse roof party asymmetrical you probably haven't heard of them, woke activated charcoal raw denim chicharrones skateboard palo santo vaporware kombucha. Man bun cred blog church-key tousled helvetica.</p>
    <p>Succulents gastropub vape portland, direct trade shabby chic cornhole. Kinfolk cornhole yuccie, food truck poke trust fund pinterest pour-over selvage normcore. Gluten-free four dollar toast edison bulb banjo, sartorial bitters sustainable vegan. Skateboard hammock hoodie hell of unicorn, jianbing actually truffaut lumbersexual sartorial. Man bun vaporware typewriter ugh, taiyaki gluten-free tbh hot chicken fingerstache cold-pressed normcore shoreditch pabst subway tile. Bushwick chartreuse roof party asymmetrical you probably haven't heard of them, woke activated charcoal raw denim chicharrones skateboard palo santo vaporware kombucha. Man bun cred blog church-key tousled helvetica.</p>
    <p>Succulents gastropub vape portland, direct trade shabby chic cornhole. Kinfolk cornhole yuccie, food truck poke trust fund pinterest pour-over selvage normcore. Gluten-free four dollar toast edison bulb banjo, sartorial bitters sustainable vegan. Skateboard hammock hoodie hell of unicorn, jianbing actually truffaut lumbersexual sartorial. Man bun vaporware typewriter ugh, taiyaki gluten-free tbh hot chicken fingerstache cold-pressed normcore shoreditch pabst subway tile. Bushwick chartreuse roof party asymmetrical you probably haven't heard of them, woke activated charcoal raw denim chicharrones skateboard palo santo vaporware kombucha. Man bun cred blog church-key tousled helvetica.</p>
    <p>Succulents gastropub vape portland, direct trade shabby chic cornhole. Kinfolk cornhole yuccie, food truck poke trust fund pinterest pour-over selvage normcore. Gluten-free four dollar toast edison bulb banjo, sartorial bitters sustainable vegan. Skateboard hammock hoodie hell of unicorn, jianbing actually truffaut lumbersexual sartorial. Man bun vaporware typewriter ugh, taiyaki gluten-free tbh hot chicken fingerstache cold-pressed normcore shoreditch pabst subway tile. Bushwick chartreuse roof party asymmetrical you probably haven't heard of them, woke activated charcoal raw denim chicharrones skateboard palo santo vaporware kombucha. Man bun cred blog church-key tousled helvetica.</p>
  </div>
);

export default IndexPage;